[package]
name = "tiff-issue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

image = "0.24.7"
fast_image_resize = "2.7.3"
fax = "0.2.0"
tiff = "*"
